<tr class="user-list" id="PaymentID_<?php echo $wo['userlist']['id'] ?>"
    data-subscription-id="<?php echo $wo['subscriptionslist']->subscription_id; ?>">
    <td><?php echo $wo['subscriptionslist']->id ?></td>
    <td>
        <a href="<?php echo $wo['site_url'] . '/@' . $wo['userlist']['username']; ?>" target="_blank">
            <img src="<?php echo GetMedia($wo['userlist']['avater']); ?>" class="setting-avatar"
                 alt="<?php echo $wo['userlist']['avater'] ?> Profile Picture">
            <?php
            $name = $wo['userlist']['first_name'] . ' ' . $wo['userlist']['last_name'];
            echo($name !== ' ' ? $name : $wo['userlist']['username']); ?>
        </a>
    </td>
    <td><?php echo $wo['subscriptionslist']->subscription_id ?></td>

    <td>
        <?php
        if ($wo['subscriptionslist']->pro_type > 0) {
            if ($wo['subscriptionslist']->pro_type == 1) {
                echo 'WEEK';
            }
            if ($wo['subscriptionslist']->pro_type == 2) {
                echo 'BASIC';
            }
            if ($wo['subscriptionslist']->pro_type == 3) {
                echo 'PREMIUM';
            }
            if ($wo['subscriptionslist']->pro_type == 4) {
                echo 'VIP';
            }
            if ($wo['subscriptionslist']->pro_type == 5) {
                echo 'VIP GOLD';
            }
            if ($wo['subscriptionslist']->pro_type == 6) {
                echo 'DIAMOND';
            }
        } ?>
    </td>
    <td><?php echo date('d M Y - H:s', $wo['subscriptionslist']->created) ?></td>
    <td><?php echo date('d M Y - H:s', $wo['subscriptionslist']->current_period_start) ?></td>
    <td><?php echo date('d M Y - H:s', $wo['subscriptionslist']->current_period_end) ?></td>

    <!--    <td><?php /*echo date('d M Y - H:s', $wo['subscriptionslist']->current_period_canceled) */ ?></td>-->
    <td>
        <?php if ($wo['subscriptionslist']->invoice_status == 'paid'): ?>
            <span class="alert alert-success">ACTIVE</span>
        <?php endif; ?>
        <?php if ($wo['subscriptionslist']->invoice_status == 'open'): ?>
            <span class="alert alert-danger">PENDING (<?php echo $wo['subscriptionslist']->invoice_status; ?> invoice)</span>
        <?php endif; ?>

    </td>

    <td>
        <button onclick="Wo_DeletePayment(<?php echo $wo['subscriptionslist']->id ?>);" type="button"
                class="btn btn-warning waves-effect waves-light">DISABLE
        </button>
        <?php if ($wo['subscriptionslist']->invoice_status == 'open'): ?>
        <button data-invoice="<?php echo $wo['subscriptionslist']->latest_invoice ?>" type="button"
                class="btn btn-info waves-effect waves-light retryIncoice">RETRY PAYMENT
        </button>
        <?php endif; ?>
        <!--<button onclick="Wo_DeletePayment(<?php /*echo $wo['subscriptionslist']->id */?>);" type="button"
                class="btn btn-danger waves-effect waves-light">DELETE
        </button>-->
    </td>
</tr>