<?php 

$page           = (!empty($_GET['page-id']) && is_numeric($_GET['page-id'])) ? Secure($_GET['page-id']) : 1;
$filter_keyword = (!empty($_GET['query'])) ? Secure($_GET['query']) : '';
$db->pageLimit  = 50;
$payments = $db->objectbuilder()->orderBy('id', 'DESC')->paginate('payments', $page);
if (($page > $db->totalPages) && !empty($_GET['page-id'])) {
  header("Location: " . Wo_LoadAdminLinkSettings('manage-payments'));
  exit();
}

?>
<div class="container-fluid">
    <div class="block-header">
        <h2>Earnings > Manage Payments</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="info-box bg-black hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">attach_money</i>
                </div>
                <div class="content">
                    <div class="text">EARNINGS</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountThisMonthPayment(); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="info-box bg-purple hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">money</i>
                </div>
                <div class="content">
                    <div class="text">CREDITS SALES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CreditsPaymentData(); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="info-box bg-black hover-expand-effect">
                <div class="icon">
                    <img src="/themes/todate/assets/img/badge/badge_1.png" style="height: 70px;margin-top: 5px;">
                </div>
                <div class="content">
                    <div class="text">WEEK SALES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllPaymentData('1'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="info-box bg-black hover-expand-effect">
                <div class="icon">
                    <img src="/themes/todate/assets/img/badge/badge_2.png" style="height: 70px;margin-top: 5px;">
                </div>
                <div class="content">
                    <div class="text">BASIC SALES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllPaymentData('2'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="info-box bg-black hover-expand-effect">
                <div class="icon">
                    <img src="/themes/todate/assets/img/badge/badge_3.png" style="height: 70px;margin-top: 5px;">
                </div>
                <div class="content">
                    <div class="text">PREMIUM SALES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllPaymentData('3'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="info-box bg-black hover-expand-effect">
                <div class="icon">
                    <img src="/themes/todate/assets/img/badge/badge_4.png" style="height: 70px;margin-top: 5px;">
                </div>
                <div class="content">
                    <div class="text">VIP SALES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllPaymentData('4'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="info-box bg-black hover-expand-effect">
                <div class="icon">
                    <img src="/themes/todate/assets/img/badge/badge_5.png" style="height: 70px;margin-top: 5px;">
                </div>
                <div class="content">
                    <div class="text">VIP GOLD SALES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllPaymentData('5'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="info-box bg-black hover-expand-effect">
                <div class="icon">
                    <img src="/themes/todate/assets/img/badge/badge_6.png" style="height: 70px;margin-top: 5px;">
                </div>
                <div class="content">
                    <div class="text">DIAMOND SALES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllPaymentData('6'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage & Edit Payments</h2>
                </div>
                <div class="body">
                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Username</th>
                                <th>Payment Type</th>
                                <th>Amount</th>
                                <th>Date</th>
                                <th>Note</th>
                                <th>Processed by</th>
                                <th>Status</th>
                                <th>Message</th>
                                <!-- <th>Action</th>-->
                            </tr>
                            </thead>
                            <tbody>
                              <?php 
                                foreach ($payments as $paymentlist) {
                                    $wo['userlist'] = Wo_UserData($paymentlist->user_id);
                                    $wo['paymentlist'] = $paymentlist;
                                    echo Wo_LoadAdminPage('manage-payments/list');
                                }
                              ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="wo-admincp-feturepager">
                      <div class="pull-left">
                        <span>
                          <?php echo "Showing $page out of " . $db->totalPages; ?>
                        </span>
                      </div>
                      <div class="pull-right">
                        <nav>
                          <ul class="pagination">
                            <li>
                              <a href="<?php echo Wo_LoadAdminLinkSettings('manage-payments?page-id=1'); ?>" class="waves-effect" title='First Page'>
                                  <i class="material-icons">first_page</i>
                              </a>
                            </li>
                            <?php if ($page > 1) {  ?>
                              <li>
                                  <a href="<?php echo Wo_LoadAdminLinkSettings('manage-payments?page-id=' . ($page - 1)); ?>" class="waves-effect" title='Previous Page'>
                                      <i class="material-icons">chevron_left</i>
                                  </a>
                              </li>
                            <?php  } ?>

                            <?php 
                              $nums       = 0;
                              $nums_pages = ($page > 4) ? ($page - 4) : $page;

                              for ($i=$nums_pages; $i <= $db->totalPages; $i++) { 
                                if ($nums < 20) {
                            ?>
                              <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                <a href="<?php echo Wo_LoadAdminLinkSettings('manage-payments?page-id=' . ($i)); ?>" class="waves-effect">
                                  <?php echo $i ?>   
                                </a>
                              </li>

                            <?php } $nums++; }?>

                            <?php if ($db->totalPages > $page) { ?>
                              <li>
                                  <a href="<?php echo Wo_LoadAdminLinkSettings('manage-payments?page-id=' . ($page + 1)); ?>" class="waves-effect" title="Next Page">
                                      <i class="material-icons">chevron_right</i>
                                  </a>
                              </li>
                            <?php } ?>
                            <li>
                              <a href="<?php echo Wo_LoadAdminLinkSettings('manage-payments?page-id=' . ($db->totalPages)); ?>" class="waves-effect" title='Last Page'>
                                  <i class="material-icons">last_page</i>
                              </a>
                            </li>
                          </ul>
                        </nav>
                      </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
<script>

function Wo_DeletePayment(payment_id) {
  if (confirm("Are you sure you want to delete this payment?") == false) {
    return false;
  }
  hash_id = '<?php echo Wo_CreateSession();?>';
  $('#PaymentID_' + user_id).fadeOut(300, function() {
    $(this).remove();
  });
  $.get(Wo_Ajax_Requests_File(),{f:'admin_setting', s:'delete_payment', payment_id: payment_id, hash_id: hash_id});
}

</script>