<div class="container-fluid">
    <div class="block-header">
        <h2>Earnings > Payments</h2>
    </div>
    <!-- Widgets -->
    <div class="row clearfix">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="info-box bg-black hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">attach_money</i>
                </div>
                <div class="content">
                    <div class="text">TOTAL EARNINGS</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllPayment(); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-black hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">attach_money</i>
                </div>
                <div class="content">
                    <div class="text">EARNINGS THIS MONTH</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountThisMonthPayment(); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-purple hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">money</i>
                </div>
                <div class="content">
                    <div class="text">CREDITS SALES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CreditsPaymentData(); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="info-box bg-black hover-expand-effect">
                <div class="icon">
                    <img src="/themes/todate/assets/img/badge/badge_1.png" style="height: 70px;margin-top: 5px;">
                </div>
                <div class="content">
                    <div class="text">WEEK SALES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllPaymentData('1'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="info-box bg-black hover-expand-effect">
                <div class="icon">
                    <img src="/themes/todate/assets/img/badge/badge_2.png" style="height: 70px;margin-top: 5px;">
                </div>
                <div class="content">
                    <div class="text">BASIC SALES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllPaymentData('2'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="info-box bg-black hover-expand-effect">
                <div class="icon">
                    <img src="/themes/todate/assets/img/badge/badge_3.png" style="height: 70px;margin-top: 5px;">
                </div>
                <div class="content">
                    <div class="text">PREMIUM SALES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllPaymentData('3'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="info-box bg-black hover-expand-effect">
                <div class="icon">
                    <img src="/themes/todate/assets/img/badge/badge_4.png" style="height: 70px;margin-top: 5px;">
                </div>
                <div class="content">
                    <div class="text">VIP SALES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllPaymentData('4'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="info-box bg-black hover-expand-effect">
                <div class="icon">
                    <img src="/themes/todate/assets/img/badge/badge_5.png" style="height: 70px;margin-top: 5px;">
                </div>
                <div class="content">
                    <div class="text">VIP GOLD SALES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllPaymentData('5'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="info-box bg-black hover-expand-effect">
                <div class="icon">
                    <img src="/themes/todate/assets/img/badge/badge_6.png" style="height: 70px;margin-top: 5px;">
                </div>
                <div class="content">
                    <div class="text">DIAMOND SALES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllPaymentData('6'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>

    </div>
    <!-- #END# Widgets -->
    <div class="row clearfix">
        <!-- Bar Chart -->
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>STATICS</h2>
                </div>
                <div class="body">
                    <div id="admin-chart-container" style="min-width: 100%; height: 400px; margin: 0 auto;"></div>
                </div>
            </div>
        </div>
        <!-- #END# Bar Chart -->
    </div>
</div>
<?php 
$percentage = (30 / 58) * 100;
//echo $percentage . "%";
$user_statics = array();
$page_statics = array();
$groups_statics = array();
$posts_statics = array();
$months = array('1','2','3','4','5','6','7','8','9','10','11','12');
// user_statics
foreach ($months as $value) {
   $user_statics[] = Wo_GetRegisteredPaymentsStatics($value, '1');
}
$user_statics = implode(', ', $user_statics);

// page_statics
foreach ($months as $value) {
   $page_statics[] = Wo_GetRegisteredPaymentsStatics($value, '2');
}
$page_statics = implode(', ', $page_statics);

// groups_statics
foreach ($months as $value) {
   $groups_statics[] = Wo_GetRegisteredPaymentsStatics($value, '3');
}
$groups_statics = implode(', ', $groups_statics);

foreach ($months as $value) {
   $posts_statics[] = Wo_GetRegisteredPaymentsStatics($value, '4');
}
$posts_statics = implode(', ', $posts_statics);
?>
<script>
   $(function () {
    Highcharts.setOptions({
      colors: ['#6abd46', '#f2b92b', '#ce3d3d', '#4c75a3', '#A73C6B', '#B52A1D']
    });
    $('#admin-chart-container').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Monthly Average'
        },
        xAxis: {
            categories: [
                'Jan',
                'Feb',
                'Mar',
                'Apr',
                'May',
                'Jun',
                'Jul',
                'Aug',
                'Sep',
                'Oct',
                'Nov',
                'Dec'
            ],
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: '<?php echo date("Y");?>'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y}</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'WEEK Sales',
            data: [<?php echo $user_statics;?>]

        }, {
            name: 'BASIC Sales',
            data: [<?php echo $page_statics;?>]

        }, {
            name: 'PREMIUM Sales',
            data: [<?php echo $groups_statics;?>]

        }, {
            name: 'VIP Sales',
            data: [<?php echo $posts_statics;?>]

        }, {
            name: 'VIP GOLD Sales',
            data: [<?php echo $posts_statics;?>]

        }, {
            name: 'DIAMOND Sales',
            data: [<?php echo $posts_statics;?>]

        }]
    });
});
</script>